name: 'JSON to MD'
description: 'Converts JSON data structure to markdown text for creating GitHub issues'
inputs:
  json-path:
    description: 'Path to JSON file containing the data (~/data.json by default)'
    required: true
    default: './data.json'
outputs:
  md-data:
    description: 'Final result parsed in markdown'
runs:
  using: 'node12'
  main: 'index.js'